version: '3.4'

services:
  api_full06:
    image: ${DOCKER_REGISTRY-}apifull06
    build:
      context: .
      dockerfile: Api_Full06/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  database:
      image: mysql:8.0.31
      container_name: mysqldb
      ports:
        - "3366:3306"
      #ports:
      #  - "3306:3306"
      expose: 
        - 3306
      volumes:
        - db-volume:/var/lib/mysql
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: api_full06
volumes:
  db-volume:
